# Repository Labels

# Default GitHub labels

- name: good first issue
  description: Good for first-time contributors
  color: 586069

# Flag labels
# Indicates additional work is needed.

- name: flag:breaking-change
  description: Contains changes that require major version bump
  color: fbca04

- name: flag:duplicate
  description: Issue, pull request, or discussion already exists
  color: fbca04

- name: flag:needs-discussion
  description: Discussion required before implementation
  color: fbca04

- name: flag:needs-docs
  description: Missing documentation or needs existing documentation update
  color: fbca04

- name: flag:needs-refactor
  description: Code improvements required before being merged
  color: fbca04

# Scope labels
# Project-specific groups for issues, pull requests, and discussions.

- name: scope:algs
  description: Algorithms
  color: 74cefc

- name: scope:big-o
  description: Algorithmic complexity / Asymptotic analysis / Big-O
  color: 74cefc

- name: scope:bst
  description: Binary search trees
  color: 74cefc

- name: scope:ci
  description: CI/CD
  color: 74cefc

- name: scope:deps
  description: Dependency updates
  color: 74cefc

- name: scope:ds
  description: Data structures
  color: 74cefc

- name: scope:graphs
  description: Graphs
  color: 74cefc

- name: scope:hash-tables
  description: Hash tables
  color: 74cefc

- name: scope:heaps
  description: Heaps
  color: 74cefc

- name: scope:linked-lists
  description: Linked lists
  color: 74cefc

- name: scope:misc
  description: Miscellaneous
  color: 74cefc

- name: scope:queues
  description: Queues
  color: 74cefc

- name: scope:recursion
  description: Recursion
  color: 74cefc

- name: scope:searching
  description: Searching
  color: 74cefc

- name: scope:sorting
  description: Sorting
  color: 74cefc

- name: scope:stacks
  description: Stacks
  color: 74cefc

- name: scope:trees
  description: Trees
  color: 74cefc

- name: scope:typescript
  description: TypeScript support (enums, interfaces, types)
  color: 74cefc

# Status labels
# Current state of an issue, pull request, or discussion.

- name: status:awaiting-answers
  description: Needs clarification or more information from author
  color: e7034b

- name: status:blocked
  description: Blocked by other work tracked in different issue
  color: e7034b

- name: status:cannot-reproduce
  description: Bug report cannot be reproduced
  color: e7034b

- name: status:fixed
  description: Fixed and merged into next, but not yet released
  color: e7034b

- name: status:has-pr
  description: Has ongoing work in an open pull request
  color: e7034b

- name: status:help-wanted
  description: Extra attention is needed
  color: e7034b

- name: status:icebox
  description: Changes that won't be implemented
  color: e7034b

- name: status:invalid
  description: No action to be taken or missing information
  color: e7034b

- name: status:merged
  description: Merged into next, but not into main (or released)
  color: e7034b

- name: status:needs-triage
  description: Needs verification and minimal reproduction
  color: e7034b

- name: status:released
  description: Merged into next, main, and released
  color: e7034b

- name: status:stale
  description: Superseded by different issue, pull request, or discussion
  color: e7034b

- name: status:wip
  description: Has ongoing work in a branch or open pull request
  color: e7034b

# Type labels
# Types of issues, pull requests, and discussions.

- name: type:build
  description: Build system or external dependencies
  color: 0052cc

- name: type:chore
  description: Housekeeping tasks / changes that don't impact external users
  color: 0052cc

- name: type:discussion
  description: Discussion topic
  color: 0052cc

- name: type:docs
  description: Improvements or additions to documentation
  color: 0052cc

- name: type:feat
  description: New feature or request
  color: 0052cc

- name: type:fix
  description: Something isn't working
  color: 0052cc

- name: type:perf
  description: Performance updates
  color: 0052cc

- name: type:question
  description: Questions
  color: 0052cc

- name: type:refactor
  description: Code improvements
  color: 0052cc
